version: '3.5'

services:
  newsfeed:
    container_name: newsfeed
    build:
      context: .
    ports:
      - "8085:8085"
    
    networks:
      - newsfeed_network
    restart: unless-stopped

  # newsfeed_rabbitmq:
  #   container_name: newsfeed_rabbitmq
  #   image: rabbitmq:management
  #   networks:
  #     - newsfeed_network
  #   restart: unless-stopped
  # newsfeed_minio:
  #   container_name: newsfeed_minio
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #     - "9002:9001"
  #   volumes:
  #     - minio_storage:/data
  #   environment:
  #     MINIO_ROOT_USER: newsfeed
  #     MINIO_ROOT_PASSWORD: newsfeed9002
  #   command: server --console-address ":9001" /data

 
  


networks:
  newsfeed_network:
    driver: bridge



